//Movies
export const FETCH_MOVIES = "FETCH_MOVIES";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const MOVIE_INFO = "MOVIE_INFO";
export const MOVIEINFO_LOADING = "MOVIEINFO_LOADING";
export const CREDITS = "CREDITS";
export const CREDITS_LOADING = "CREDITS_LOADING";
export const GET_ACTOR_DETAILS = "GET_ACTOR_DETAILS";
export const GET_ACTOR_IMAGES = "GET_ACTOR_IMAGES";
export const ACTOR_DETAILS_LOADING = "ACTOR_DETAILS_LOADING";
export const IMAGES_LOADING = "IMAGES_LOADING";
export const GET_WATCH_PROVIDERS = "GET_WATCH_PROVIDERS";
export const GET_WATCH_PROVIDERS_LOADING = "GET_WATCH_PROVIDERS_LOADING";
export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_NOW_PLAYING_MOVIES = "GET_NOW_PLAYING_MOVIES";
//Tv Shows
export const FETCH_TV_SHOWS = "FETCH_TV_SHOWS";
export const TVSHOW_INFO = "TVSHOW_INFO";
export const TV_CREDITS = "TV_CREDITS";
export const GET_TVSHOW_WATCH_PROVIDERS = "GET_TVSHOW_WATCH_PROVIDERS";
export const TVSHOW_INFO_LOADING = "TVSHOW_INFO_LOADING";
export const TV_CREDITS_LOADING = "TV_CREDITS_LOADING";
export const SEARCH_TVSHOW = "SEARCH_TVSHOW";
