export const FETCH_MOVIES = "FETCH_MOVIES";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const MOVIE_INFO = "MOVIE_INFO";
export const MOVIEINFO_LOADING = "MOVIEINFO_LOADING";
export const CREDITS = "CREDITS";
export const CREDITS_LOADING = "CREDITS_LOADING";
